
title: Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Ravi K. Patel  ## put your name
title: 'PhD Student - Genomics'  ## your title
location: Ithaca, NY


## Social Profiles
facebook: https://www.facebook.com/ravi.patel.86  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/ravi-patel-b9883997/  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
